version: '3'

services:
  friday-ddns:
    image: ghcr.io/arxxyr/friday-ddns:amd64
    container_name: friday-ddns
    restart: unless-stopped
    network_mode: "host"  # 使用host网络模式
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - /mnt/config/ddns/config.yaml:/etc/friday-ddns/config.yaml:ro
    # 使用更健壮的方式运行定时任务
    command: 
      - "bash"
      - "-c"
      - |
        echo "首次运行DDNS更新..."
        friday-ddns -c /etc/friday-ddns/config.yaml
        echo "设置定时任务，每15分钟运行一次..."
        while true; do
          sleep 900
          echo "运行定时DDNS更新..."
          friday-ddns -c /etc/friday-ddns/config.yaml || echo "更新失败，将在下次尝试"
        done 