FROM rustlang/rust:nightly AS builder

WORKDIR /usr/src
COPY . .

RUN cargo build --release

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /usr/src/target/release/friday-ddns /usr/local/bin/friday-ddns

RUN mkdir -p /etc/friday-ddns

ENTRYPOINT ["friday-ddns", "-c", "/etc/friday-ddns/config.yaml"] 